### ISSUE TITLE
Weird Culture bug

### ISSUE THREAD

**Issue by sander1095** [sander1095/DnDInitiativeTracker#15]
```
ERROR DETAILS
    Following errors were detected during this operation.  
    * [2/6/2017 2:34:32 PM] System.Globalization.CultureNotFoundException  
        - Culture is not supported.  
Parameter name: name  
aa-DJ is an invalid culture identifier.  
        - Source: mscorlib  
        - Stack trace:  
            at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
            at System.Deployment.Application.AssemblyMetaDataImport.ConstructAssemblyName(IntPtr asmMetaPtr, Char[] asmNameBuf, UInt32 asmNameLength, IntPtr pubKeyPtr, UInt32 pubKeyBytes, UInt32 flags)
            at System.Deployment.Application.AssemblyMetaDataImport.ImportIdentity()
            at System.Deployment.Application.AssemblyMetaDataImport.get_Name()
            at System.Deployment.Application.Manifest.AssemblyManifest.LoadFromCompLibAssembly(String filePath)
            at System.Deployment.Application.Manifest.AssemblyManifest.LoadFromInternalManifestFile(String filePath)
            at System.Deployment.Application.DownloadManager.ProcessDownloadedFile(Object sender, DownloadEventArgs e)
            at System.Deployment.Application.FileDownloader.DownloadModifiedEventHandler.Invoke(Object sender, DownloadEventArgs e)
            at System.Deployment.Application.FileDownloader.OnModified()
            at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
            at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
            at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
            at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
            at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
            at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
            at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
            at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
Here's the platform info:
PLATFORM VERSION INFO
    Windows             : 6.1.7601.65536 (Win32NT)
    Common Language Runtime     : 4.0.30319.42000
    System.Deployment.dll       : 4.6.1087.0 built by: NETFXREL4STAGE
    clr.dll             : 4.6.1087.0 built by: NETFXREL4STAGE
    dfdll.dll           : 4.6.1087.0 built by: NETFXREL4STAGE
    dfshim.dll          : 4.0.41209.0 (Main.041209-0000)
```

Someone on Reddit reported this issue. I am sure it has something to do with the `OverviewForm.aa-DJ.resx` file but I still need to find out how it got there and how to fix it

**Comment by medavisjr** [comment]
Hi, this is the reddit poster who originally encountered this issue.

Good news! InitiativeTracker 2.0 (shows 1.0.0.3 and 1.0.0.4 folders in the application files) from the Dec 27, 2016 release installed just fine. So whatever the problem is, it must be due to a change in the latest release. My culture is United States/English (US) if that helps.

Let me know if there's any other info you need. Thanks for your work!

**Comment by sander1095** [comment]
Should have been fixed in the latest release. Let me know if it still doesn't work!

**Comment by medavisjr** [comment]
It's fixed! Thanks!
